# Generated by Django 5.0.3 on 2024-05-28 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=50)),
                ('APIkey', models.CharField(max_length=50)),
                ('instructions', models.CharField(max_length=255)),
            ],
        ),
    ]
